version: '3'
services:
  web:
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - "./src:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        php_version: ${PHP_VERSION}
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}